// <auto-generated />
namespace ruanj1801.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Users201911281438 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Users201911281438));
        
        string IMigrationMetadata.Id
        {
            get { return "201911280640166_Users201911281438"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
